export const FETCH_OK = "FETCH_OK";
export const FETCH_ERR = "FETCH_ERR";
export const REMOVE_ARTIST = "REMOVE_ARTIST";
export const SELECT_SONG = "SELECT_SONG";
export const SEARCH_ARTIST = "SEARCH_ARTIST";
export const ADD_FAVOURITES = "ADD_FAVOURITES";
export const REMOVE_FAVOURITES = "REMOVE_FAVOURITES";
